### ISSUE TITLE
[design thot]

### ISSUE THREAD

**Issue by edouerd** [dumblr/linkstream#5]
Perhaps we give linkstream feed/stream a max width because of this:

![screen recording 2018-07-30 at 20 54](https://user-images.githubusercontent.com/1195363/43431267-0624bb06-943b-11e8-876a-ed13556ddd66.gif)

If i get some time i could probably send a pr over w/ a proposed fix ... maybe

**Comment by nickbytes** [comment]
Honestly, I picked a pretty arbitrary number, so if something feels better to you, let me know.
